version: "3.4"
services:
  docnet:
    build: .                    # Build the service from the Dockerfile in the current directory
    container_name: fil_rouge    # Name of the container
    restart: always              # Restart policy
    ports:
      - "1998:1998"              # Map host port 1998 to container port 1998
    depends_on:
      - postgresdb               # Ensure PostgreSQL starts before this service

  postgresdb:
    image: "postgres:latest"     # Use the latest PostgreSQL image
    restart: always              # Restart policy
    ports:
      - "5432:5432"              # Map host port 5432 to container port 5432
    environment:
      POSTGRES_DB: Fitness       # Name of the database
      POSTGRES_USER: postgres    # Default user
      POSTGRES_PASSWORD: ader12  # Default password
    volumes:
      - db:/var/lib/postgresql/data  # Persist PostgreSQL data

volumes:
  db:                            # Define a named volume for PostgreSQL
